USE SisDep;

SELECT
	F.NOMEFUNCIONARIO,
	D.NOMEDEPENDENTE,
	D.NASCIMENTODEPENDENTE
FROM FUNCIONARIO AS F LEFT OUTER JOIN DEPENDENTE AS D
ON F.IDMATRICULA = D.IDMATRICULA;


SELECT
	F.NOMEFUNCIONARIO,
	C.NOMECARGO,
	F.SALARIO
FROM FUNCIONARIO AS F RIGHT JOIN CARGO AS C
ON F.IDCARGO = C.IDCARGO
WHERE F.NOMEFUNCIONARIO IS NULL;